name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 113.167.117.46
          username: trungn1
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./baocaoantoan/
          server-dir: /htdocs/antoan-msi.io.vn/
          exclude: |
            **/.git*
            **/.git*/**
            **/backup/**
            **/.claude/**
